package brickbreaker;

/**
 * Required imports
 */
import java.awt.Color;

/**
 * BrickBreakerStartForm.java - This form asks for user to press the start 
 * button to play brick breaker game.
 *
 * @author Abhishek Shah
 * @since Jan. 5, 2020
 */
public class BrickBreakerStartForm extends javax.swing.JFrame {

    /**
     * Creates new form BrickBreakerStartForm
     */
    public BrickBreakerStartForm() {
        initComponents();
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Brick Breaker Game");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 420, 80);

        btnStart.setBackground(new java.awt.Color(0, 0, 204));
        btnStart.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 0));
        btnStart.setText("START");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(110, 160, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start() {
        // Some settings for the form
        this.setTitle(Globals.APPLICATION_TITLE);
        this.setResizable(false);
        this.setSize(440, 345);
        this.setLocationRelativeTo(null);
        this.setBackground(Color.black);
        this.getContentPane().setBackground(Color.black);
        this.setVisible(true);
    }

    /**
     * When the mouse is clicked it should switch the form
     *
     * @param evt opens the new game form
     */
    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        BrickBreakerForm screen = new BrickBreakerForm();
    }//GEN-LAST:event_btnStartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
